### ISSUE TITLE
Send later feature

### ISSUE THREAD

**Issue by wmnnd** [pentacent/keila#11]
Instead of sending campaigns immediately, there should be an option to automatically send campaigns at a later date.

This should be implemented as an Oban scheduled job.

- [x] Implement `Mailings.campaign_deliver_later` with Oban scheduled job for sending
- [x] Implement interface for scheduling campaigns from campaign editor. Include option to select timezone.

**Comment by Jcambass** [comment]
@wmnnd What's your take on using scheduled jobs vs using a periodic CRON job to deliver mails?

I first wanted to go for a CRON job solution but I wonder if it is already worth it to go that route.
I collected the following pros/cons:

**Scheduled Job**

Pros:
- Can be unique to make sure we don't send the campaign twice (already handled somewhat but still nice to have).
- Concurrency is limited by the queue configuration.

Cons:
- Fills up the queue with jobs that potentially stay around for long.
- Knowledge that the campaign has been scheduled for delivery needs to be duplicated (the job and a column in the campaign).-

**CRON job**

Pros:
- One source of truth. We only need the `deliver_at` column in campaigns to know that a campaign has been scheduled and when it has to be sent.
- Only one job is inserted periodically to poll for campaigns that need to be delivered.
- We can finetune the poll interval for campaigns.

Cons:
- We need to handle max concurrency ourselves.
- We need to make a tradeoff between limiting the number of campaigns to deliver on each interval and the duration of the interval.

I originally was thinking that a periodic cron job would be better but I think it really depends on how time accurate we need to be and on how many scheduled campaigns we expect. What do you think?

**Comment by wmnnd** [comment]
Thanks for the write-up!

I still like your suggestion of using a single source of truth (`deliver_at`) in combination with periodic checks whether a campaign should be sent. Oban supports CRON-style jobs, so this should also be pretty straightforward to implement. And an interval of once every minute or once every five minutes should not add too much overhead.
Since sending a campaign will always take a while if you have lots of recipients, I don’t think higher granularity would make sense.

At this stage, I’m also not super concerned about the concurrency implications.
I think eventually we’ll have to find a solution to make sure that campaigns are not being sent purely based on FIFO but instead implement something that allows multiple campaigns to be delivered at the same time (i.e. instead of delivering campaigns A and B as `AAAAAABBBBB`, deliver them as `ABABABABABA`). But this is beyond the scope of this issue and something we’ll have to implement regardless of the approach we choose.

Or was your concern more about the fact that several campaigns with many thousands of recipients might potentially end up getting created at the same time and thus overloading the database? Ecto should handle this with its connection pooling, shouldn’t it?

**Comment by Jcambass** [comment]
Yes I was mostly worried around to many concurrent checkout attempts of db connections but after checking the docs it indeed looks like ectos db pooling doed'nt have a wait-timeout so we just block until we get a connection.

One downside would still be that if we start a task for campaign A and we don't get the chance to deliver it (update `sent_at`) before the next periodic job is run, we will create a new task for campaign A. The locking introduced in a previous PR will guarantee that we keep data consistency but we will still create a backlog eith tasks that want to checkout db connections since we potentially have a unbound set of tasks.

One thing to somewhat mitigate that is to only ever deliver n campaigns on each iteration. The problem can still occur but we have at least some control.

**Comment by wmnnd** [comment]
If the cron worker operates in a different queue from the sending queue, then I’m not too worried about the scheduling jobs piling up. They will be able to quickly skip campaigns that are already being delivered and your implementation of locks gives us a strong guarantee of that.

I was imagining the worker to simply do something like this:

```elixir
all_scheduled_campaigns()
|> Enum.each(fn campaign ->
  Mailing.deliver_campaign_async(campaign.id)
end)
```

So the worker doesn’t care if a campaign is already being delivered, everything would be handled just like a manual trigger of the delivery through the UI.
And in a worst-case scenario with the server being completely overloaded for an entire hour, we might end up with n * 60 (or n * 12) tasks waiting to execute, but OTP can handle 32,768 concurrent processes (which can be configured to be increased up to 268,435,456) , so I think we’re in the clear.

**Comment by Jcambass** [comment]
I guess I'm not yet used to have the guarantees of OTP. Still on a larger scale it's not ideal to have tens of thousands processes fighting for resources like db connections just to noop later.

I guess we can use this naiv approach to start and extend it if ever needed. Maybe adding telemetry and structured logging would be helpful to see how the numbers look like in a production env.

Out of curiosity.. do you plan to offer Keila as a hosted SaaS? Just to get a idea of the size we're optimizing for :)

**Comment by wmnnd** [comment]
Yes, Telemetry sounds like a good idea! We could make use of the Phoenix Live Dashboard and display stats about the queues there.
And also yes to your other question, I am planning on offering a hosted version eventually. But until the point at which that instance would get tens of thousands of concurrent campaigns I think there’s more than enough time to add some optimizations :smile:

**Comment by Jcambass** [comment]
@wmnnd Do you think we should allow users to reschedule an already scheduled campaign? I think it would be useful but it opens a can of worms since we can't guarantee that we didn't already schedule a job to deliver it but it hasn't been executed yet and therefore no `sent_at` is present yet. We can try to guard against this in the worker (by checking the `deliver_at` again) but I was wondering if we want to support that in the first place.

**Comment by wmnnd** [comment]
Good question!
I think it should be possible to reschedule campaigns.

The most important thing in all cases is to avoid sending a campaign twice. This is already taken care of with database locking.

Now, rescheduling a campaign that the worker is in the process of preparing for sending out is certainly an edge case. I feel it might best be solved by the UI, e.g. by disabling the option to reschedule a campaign one minute before the scheduled sending time. 

What do you think?

**Comment by Jcambass** [comment]
Blocking the UI can decrease the chance of it happening but not eliminating it. I was under the wrong impression that we set the `sent_at` in the oban worker but we actually do it inline when delivering a campaign, so there is a very tiny window where this situation of rescheduling but sending still occurs via the previous `deliver_at` could happen. So I think we're fine.

**Comment by wmnnd** [comment]
Implemented via #32 + #34
